version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
   - location: scripts/before_install.sh
     timeout: 300
     runas: root

  AfterInstall:
    - location: scripts/build.sh
      timeout: 300
      runas: root


